baseURL = "https://ystk0731.github.io/"
languageCode = "ja-jp"
title = "My Memo Site"
theme = "gohugo-theme-ananke"

copyright="ystk0731"
googleAnalytics = ""
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true

[params.intro]
  main = "Hi, I'm ystk"
  sub = "I'm a System Enginer"


[params]
  breadcrumb = true
  accentColor = "#FD3519"
  mainSections = ['portfolio']


[menu]

[[menu.main]]
  identifier = "about"
  name = "About"
  title = "About section"
  url = "/about/"
  weight = -120

[[menu.main]]
  identifier = "portfolio"
  name = "Portfolio"
  title = "Portfolio"
  url = "/portfolio/"
  weight = -110

[[menu.main]]
  identifier = "blog"
  name = "Post"
  title = "Blog section"
  url = "/posts/"
  weight = -100


